[package]
name = "gecko-media"
version = "0.1.0"
authors = ["Chris Pearce <cpearce@mozilla.com>"]
build = "build.rs"

[build]
rustflags = ["-C link-arg=-fno-exceptions"]


[dependencies]

[build-dependencies]
gcc = "0.3.53"
